### ISSUE TITLE
report format suggestions

### ISSUE THREAD

**Issue by RichMorin** [akoutmos/doctor#1]
I'd change the headings to use title case (e.g., "Spec Cov"), for readability.

The lines are too long for convenient printing, viewing, etc.  I'd suggest breaking them into line pairs. For example, File could go below Module, Spec Cov below Doc Cov, etc. I'd also shorten headings (e.g., Functions) which are much longer than the data fields.

Because these changes would allow room for additional fields, the report could add information on macros, private vs. public functions, etc. Here is a rough idea of what a changed format might look like:

    Cov.  Module/File               F/M  D/S  MD
    67%   Common.Maps               6    2    Y     
    0%    lib/common/maps.ex        0    6

**Comment by akoutmos** [comment]
I added an additional reporter in #3 to be less verbose. You can invoke the less verbose reporter by running `mix doctor --short`.

**Comment by akoutmos** [comment]
You can find the fixes to your issues in version 0.6.0 which was just released. Thanks again for the feedback!
