### ISSUE TITLE
Feature Request - Retrieving the configuration file from the config folder

### ISSUE THREAD

**Issue by ImNotAVirus** [akoutmos/doctor#14]
Currently, Doctor searches for its configuration file only from the project root folder.
However, many Alchemists (including me) like to have their configuration files in the same place: in the `config` directory.

The purpose of this issue is to find out if it would be possible for Doctor to check in addition to the root directory, the `config` directory in order to see if the configuration file is there.

Thanks and have a nice day!

**Comment by akoutmos** [comment]
While I don't trust that you are not a virus....I can see why you need that feature :P.

Would you imagine it looks like how credo has this implemented? i.e have a `--config-file` option along with a path to the config file?

**Comment by ImNotAVirus** [comment]
That's exactly what I was thinking!
Having a `--config-file` option would be perfect

**Comment by akoutmos** [comment]
You've got it! Should have something put together by EOD today or tomorrow with a release cut. Thanks for the feature request!

**Comment by akoutmos** [comment]
@ImNotAVirus I went ahead and made a branch with your requested changes. Could you change your mix.exs doctor dep to: {:doctor, git: "https://github.com/akoutmos/doctor", branch: "help_and_config_file"} and then run `mix doctor --config-file <PATH_TO_YOUR_FILE>` to make sure things look right?

Thanks!

**Comment by ImNotAVirus** [comment]
It's perfectly working! Thank you!

**Comment by akoutmos** [comment]
Version `0.12.0` has been published to Hex https://hex.pm/packages/doctor. Check out the changelog for all the additional features that made it into the release. Thanks for the feedback again and enjoy!
