### ISSUE TITLE
Comparison to Inch in README

### ISSUE THREAD

**Issue by lpil** [akoutmos/doctor#22]
Hello!

Would it be possible to include a comparison to Inch? https://github.com/rrrene/inch_ex

Upon first inspection it's not obvious to a newcomer such as myself how to decide between Doctor and Inch.

Thank you

**Comment by akoutmos** [comment]
That's a good idea! There is a little bit of over lap between doctor/credo/inch so it would probably be helpful for users to know what tool is applicable in what situation. I'll add something to the README later today.

Appreciate the feedback :)

**Comment by lpil** [comment]
Thank you :)

**Comment by akoutmos** [comment]
Documentation has been updated to address the differences between Doctor/Inch/Credo https://github.com/akoutmos/doctor#comparison-with-other-tools. Closing this issue for now. Feel free to reopen if I missed anything. Thanks!
