### ISSUE TITLE
Switch from Travis to GitHub Actions

### ISSUE THREAD

**Issue by akoutmos** [akoutmos/doctor#30]

**Comment by karolsluszniak** [comment]
:+1: I've made a similar switch in ex_check some time ago and it was definitely worth it - queue times are much shorter so the feedback loop gets supercharged. 

It may be helpful for you (or anyone interested in solving this issue) to take a look at & compare both CI configs at https://github.com/karolsluszniak/ex_check#continuous-integration.

Btw in the end I've decided not to unplug Travis and to add separate README badge for each CI. Aside from its longer queue times, there were cases when Travis was working when GitHub wasn't e.g. when setup-elixir action was failing for a whole day like in [this build](https://github.com/karolsluszniak/ex_check/runs/1599584468?check_suite_focus=true).

**Comment by akoutmos** [comment]
That has been my experience as well. From the get-go with PromEx I used GitHub Actions (https://github.com/akoutmos/prom_ex) and I have had a far better experience. I'll probably port over that yaml definition in the coming weeks given that it is pretty stable.
