### ISSUE TITLE
Elixir 1.8+ required due to use of Mix.Task.recursing?

### ISSUE THREAD

**Issue by karolsluszniak** [akoutmos/doctor#33]
Hi there! Great work on this library, I've just discovered it via https://akoutmos.com/post/elixir-cicd (also great, quality stuff) and opened https://github.com/karolsluszniak/ex_check/pull/26 to add it as a default curated tool in ex_check so that more Elixir developers may discover it and include docs in their CI checklist.

And since ex_check's test suite runs on Elixir 1.7 and 1.10, the former has discovered that doctor suffers from issue similar to this one: https://github.com/xerions/phoenix_swagger/issues/242 - i.e. use of Mix.Task.recursing? requires Elixir 1.8+ even though doctor declares 1.7+ in mix.exs.

<img width="959" alt="Zrzut ekranu 2021-01-11 o 16 46 36" src="https://user-images.githubusercontent.com/1230951/104203566-9630b200-542c-11eb-9a26-b1a7aaa154b9.png">

I'll cover this issue on ex_check's side by only activating doctor in Elixir 1.8+.

**Comment by akoutmos** [comment]
Good catch! And a huge thanks for considering adding Doctor to ex_check :+1:. That is awesome news and I think the community will benefit from having healthy documentation ;). I just published 0.17.0 to hex and bumped the Elixir version requirement to 1.8 as you suggested.

Looking forward to seeing karolsluszniak/ex_check#26 merged in. Thanks!
