### ISSUE TITLE
"Doc Cov" is missing some `@doc` entries

### ISSUE THREAD

**Issue by RichMorin** [akoutmos/doctor#4]
Using the new `--short` format (yay!), I generated another set of reports for my project (https://github.com/RichMorin/PA_all). I am mystified, however, by the fact that doctor only finds four of the six `@doc` entries in this file:

    Doc Cov  Spec Cov  Functions  Module                                   Module Doc
    67%      100%      6          Common.Maps                              YES

**Comment by akoutmos** [comment]
Just to make sure we are talking about the same file. Is this it https://github.com/RichMorin/PA_all/blob/master/PA_elixir/server/apps/common/lib/common/maps.ex?

If so I only see 4 `@doc` annotations.

**Comment by RichMorin** [comment]
Ah; I need to have an `@doc` entry for each arity of each function.

**Comment by akoutmos** [comment]
That's correct. Doctor checks to see if each function and each arity of that function has docs. If you have a function with several pattern match heads defined but of the same arity, doctor only requires that 1 doc exist.
