### ISSUE TITLE
doctor crashes; passes nil to Decimal.to_float/1

### ISSUE THREAD

**Issue by RichMorin** [akoutmos/doctor#6]
When I run doctor 0.7, either with or without the `--short` option, I get a crash:

    $ mix doctor --short
    ==> common
    Doctor file not found. Using defaults.
    ---------------------------------------------------------------------------------
    Doc Cov  Spec Cov  Functions  Module                                   Module Doc
    ** (FunctionClauseError) no function clause matching in Decimal.to_float/1    
    
    The following arguments were given to Decimal.to_float/1:
    
        # 1
        nil
    
    Attempted function clauses (showing 1 out of 1):
    
        def to_float(%Decimal{sign: sign, coef: coef, exp: exp})
          when is_integer(coef)
    
    (decimal) lib/decimal.ex:1397: Decimal.to_float/1
    lib/report_utils.ex:90: Doctor.ReportUtils.module_passed_validation?/2
    lib/reporters/short.ex:39: anonymous fn/2 in Doctor.Reporters.Short.generate_report/2
    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:769: Enum.each/2
    lib/reporters/short.ex:25: Doctor.Reporters.Short.generate_report/2
    lib/cli/cli.ex:35: Doctor.CLI.run_report/1
    lib/mix/tasks/doctor.ex:22: Mix.Tasks.Doctor.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/project.ex:348: Mix.Project.in_project/4
    (elixir) lib/file.ex:1506: File.cd!/2
    (mix) lib/mix/task.ex:431: anonymous fn/4 in Mix.Task.recur/1
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix) lib/mix/task.ex:430: Mix.Task.recur/1
    (mix) lib/mix/project_stack.ex:208: Mix.ProjectStack.recur/1
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2

**Comment by akoutmos** [comment]
I think I see what the issue is. I'll fix it tonight along with a test and create a new release. Thanks!

**Comment by akoutmos** [comment]
Just published 0.8.0 which addresses this issue. I also added additional tests to ensure this isn't an issue going forward. Thanks again for the feedback :)

**Comment by RichMorin** [comment]
You rock! I just changed my dependencies and ran `mix doctor --short`. Got a nice report and no crash.

**Comment by akoutmos** [comment]
Glad to hear it!
